### ISSUE TITLE
Feature request - lowercase page title

### ISSUE THREAD

**Issue by Bumbadawg** [Reiiii/no-caps-firefox#2]
So you might have one day opened your Youtube links in a tree style tab manner and gazed at a spree of **"CAPS-LOCK 10 THINGS YOU WOULDN'T BELIEVE ARE ACTUALLY TRUE"** kind of youtube tabs.
Is it possible to get tabs titles to lowercase as well. Maybe as in Lowercase and not lowercase. Thanks for this addon by the way :)

**Comment by Bumbadawg** [comment]
So you might have one day opened your Youtube links in a tree style tab manner and gazed at a spree of "CAPS-LOCK 10 THINGS YOU WOULDN'T BELIEVE ARE ACTUALLY TRUE" kind of youtube tabs.

**Comment by Reiiii** [comment]
that happens because the addon only changes the title on page load.
some sites like youtube change the title later after load.

i'm gonna look into how i could do it without sacrificing any performance.

**Comment by Bumbadawg** [comment]
hehe fast answer.
Yes adding a checkCallback with delay might do the trick if you want it fast and dirty.
if you want it clean and proper adding an object watch like here might do it https://gist.github.com/eligrey/384583

**Comment by Reiiii** [comment]
an object watch might not work for this case because it's made for javascript object and not dom objects.
a mutationobserver is probably the solution that's best for this.
i'm gonna try to implement something like that tomorrow.

**Comment by Bumbadawg** [comment]
Thanks for the changes, i tested it and it works great!

Is it possible to change first character to capital ?
`function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1).toLowerCase();
}`

**Comment by Reiiii** [comment]
thanks for the feedback!

it would be possible to do that, but capitalizing letters isn't in the spirit of this addon and thus, wouldn't really fit.
